import { DefaultTheme } from "react-native-paper";

export const lightTheme = {
  ...DefaultTheme,
  dark: false,
  mode: "adaptive",
  colors: {
    primary: "rgba(119, 110, 100, 1)",
    background: "rgba(255, 255, 255, 1)",
    secondary: "rgba(0, 0, 0, 1)",
    Primary_Dark_70: "rgba(0, 21, 4, 1)",
    Primary_Dark_80: "rgba(0, 34, 6, 1)",
    tertiary: "rgba(224, 79, 57, 1)",
    surface: "rgba(255, 255, 255, 1)",
    error: "rgba(255, 96, 96, 1)",
    outline: "rgba(110, 99, 138, 1)",
    divider: "rgba(203, 203, 203, 1)",
    surfaceDisabled: "rgba(119, 110, 100, 1)",
    fill: "rgba(110, 99, 138, 1)",
    disabled: "rgba(110, 99, 138, 0.2)",
    profileBadge: "rgba(242, 242, 242, 1)",
    primaryDark_100: "rgba(60, 110, 82, 1)",
    secondary_90: "rgba(119, 110, 100, 1)",
    Secondary_80: "rgba(182, 177, 197, 1)",
    Secondary_100: "rgba(224, 79, 57, 1)",
    chatBoxBacground: "rgba(242, 242, 242, 1)",
    Neutral_6: "rgba(121, 124, 123, 1)",
  },

  fonts: {
    labelSmall: {
      fontFamily: "Roboto",
      letterSpacing: 1,
      fontWeight: "500",
      lineHeight: 0,
      fontSize: 13,
    },
    labelMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 1,
      fontWeight: "600",
      lineHeight: 0,
      fontSize: 16,
    },
    labelLarge: {
      fontFamily: "Mulish",
      letterSpacing: 0,
      fontWeight: "300",
      lineHeight: 0,
      fontSize: 36,
    },
    bodySmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 13,
    },
    bodyMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    displayLarge: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    displaySmall: {
      fontFamily: "Mulish-Light",
      letterSpacing: 0,
      lineHeight: 0,
      fontSize: 13,
    },
    displayMedium: {
      fontFamily: "Mulish-Light",
      letterSpacing: 0,
      fontWeight: "300",
      lineHeight: 0,
      fontSize: 17,
    },
    headlineSmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    headlineMedium: {
      fontFamily: "Mulish-Medium",
      letterSpacing: 0,
      fontWeight: "600",
      lineHeight: 0,
      fontSize: 17,
    },
    headlineLarge: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    titleSmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    titleLarge: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    titleMedium: {
      fontFamily: "Roboto-Medium",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    // bodyLarge: {
    //   fontFamily: "Mulish-Regular",
    //   letterSpacing: 0,
    //   fontWeight: "400",
    //   lineHeight: 0,
    //   fontSize: 30,
    // },
  },
};

export const darkTheme = {
  dark: true,
  mode: "adaptive",
  colors: {
    primary: "rgba(137, 187, 159, 1)",
    // background: "#1A1A1A",
    background: "rgba(255, 255, 255, 1)",
    secondary: "rgba(0, 22, 24, 1)",
    Primary_Dark_70: "rgba(0, 21, 4, 1)",
    Primary_Dark_80: "rgba(0, 34, 6, 1)",
    tertiary: "rgba(231, 242, 242, 1)",
    surface: "rgba(255, 255, 255, 1)",
    error: "rgba(255, 96, 96, 1)",
    outline: "rgba(110, 99, 138, 1)",
    divider: "rgba(203, 203, 203, 1)",
    surfaceDisabled: "rgba(184, 214, 197, 1)",
    fill: "rgba(110, 99, 138, 1)",
    disabled: "rgba(110, 99, 138, 0.5)",
  },

  fonts: {
    labelSmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 1,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 13,
    },
    labelMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 1,
      fontWeight: "600",
      lineHeight: 0,
      fontSize: 17,
    },
    labelLarge: {
      fontFamily: "weblysleekuil",
      letterSpacing: 0,
      fontWeight: "300",
      lineHeight: 0,
      fontSize: 36,
    },
    bodySmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 13,
    },
    bodyMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    displayLarge: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    displaySmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    displayMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    headlineSmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    headlineMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    headlineLarge: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    titleSmall: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    titleLarge: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
    titleMedium: {
      fontFamily: "Mulish-Regular",
      letterSpacing: 0,
      fontWeight: "400",
      lineHeight: 0,
      fontSize: 15,
    },
  },
};
